services:
  - type: web
    name: prysm-backend
    env: node
    plan: starter
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://user1:bro12345@cluster0.cytksem.mongodb.net/password-manager
      - key: PORT
        value: 10000
    healthCheckPath: /health
